using System;
using System.Collections.Generic;
using System.Linq;
using CommunityToolkit.Mvvm.ComponentModel;
using H;
using H.Generators.Extensions;
using Kava.Generators.Abstractions;
using Kava.Generators.Attributes;
using Kava.Generators.Extensions;
using Microsoft.CodeAnalysis.Diagnostics;

namespace Kava.Generators.Sources;

[Generator]
public sealed class StaticViewLocatorGenerator
    : SourceGeneratorForTypeWithAttribute<StaticViewLocatorAttribute>
{
    protected override string Id => "SVLG";

    protected override IEnumerable<FileWithName> StaticSources =>
        [
            new(
                $"{typeof(StaticViewLocatorAttribute).FullName}",
                Resources.StaticViewLocatorAttribute_cs.AsString().AddAutoGeneratedMessage()
            ),
        ];

    protected override string GenerateCode(
        Compilation compilation,
        TypeDeclarationSyntax node,
        INamedTypeSymbol symbol,
        StaticViewLocatorAttribute attribute,
        AnalyzerConfigOptions options
    )
    {
        var targetSymbol = compilation.GetTypeByMetadataName(typeof(ObservableObject).FullName!);

        var viewModelSymbols = compilation
            .GlobalNamespace.CollectTypeSymbols(targetSymbol)
            .Where(x => !x.IsAbstract)
            .OrderBy(x => x.ToDisplayString());

        var source = new SourceStringBuilder(symbol);

        source.Line();
        source.Line("using System;");
        source.Line("using System.Collections.Generic;");
        source.Line("using Avalonia.Controls;");
        source.Line("using Avalonia.Controls.Templates;");
        source.Line();

        source.PartialTypeBlockBrace(
            "IDataTemplate",
            () =>
            {
                source.Line(
                    "public static Dictionary<Type, Func<object, Control>> ViewMap { get; } = new()"
                );
                source.BlockDecl(() =>
                {
                    foreach (var viewModelSymbol in viewModelSymbols)
                    {
                        var view = GetView(viewModelSymbol, compilation);

                        if (view is null)
                            continue;

                        source.Line(
                            $"[typeof({viewModelSymbol.ToFullDisplayString()})] = (viewModel) => new {view.ToFullDisplayString()}() {{ ViewModel = ({viewModelSymbol.ToFullDisplayString()})viewModel }},"
                        );
                    }
                });
            }
        );

        return source.ToString();
    }

    private static INamedTypeSymbol? GetView(ISymbol symbol, Compilation compilation)
    {
        var viewName = symbol.ToDisplayString().Replace("ViewModel", "View");
        var viewSymbol = compilation.GetTypeByMetadataName(viewName);

        if (viewSymbol is not null)
            return viewSymbol;

        viewName = symbol.ToDisplayString().Replace(".ViewModels.", ".Views.");
        viewName = viewName.Remove(viewName.IndexOf("ViewModel", StringComparison.Ordinal));
        return compilation.GetTypeByMetadataName(viewName);
    }
}
